### ISSUE TITLE
Add project name field to plugin details

### ISSUE THREAD

**Issue by lol768** [BukGet/generator#1]
Project name is given by the CSS selector `#hd > h1` on the project's main page.

This could be added to http://api.bukget.org/3/plugins/bukkit/{some slug}

I've seen projects before where multiple plugin files are uploaded (e.g. a lite/full version) and the names in the plugin.yml would differ to the project name.

**Comment by DMarby** [comment]
Closing this due to the project not being active anymore, please see https://bukget.org/news/BukGet-Winding-Down/ for more details.
