### ISSUE TITLE
Add support for Spigot Resources

### ISSUE THREAD

**Issue by rlf** [BukGet/generator#5]
Some plugins has moved from dev.bukkit to Spigotmc.org during the meltdown at dev.bukkit.

Some are back, but not all.

Could we make/get a scraper/generator for the Spigot resources?

**Comment by SteveMcGrath** [comment]
We have been specifically asked NOT to build a webscraper for Spigot so not to cause undue load on their Xenforo system.

**Comment by rlf** [comment]
I'll try to lobby them providing an API in the Xenforo instead then.

**Comment by SteveMcGrath** [comment]
As an update to this, please see https://github.com/BukGet/api/issues/106
