### ISSUE TITLE
Spigotmc

### ISSUE THREAD

**Issue by MTRNord** [BukGet/generator#6]
Whats about an support for SpigotMC Plugins? Is that planned?

**Comment by SteveMcGrath** [comment]
It is not.  There isn't a good way to get all of the data from the backend without effectively web scraping.  You have to remember that BukGet is originally intended to be a stop-gap until the server binary devs collectively got their heads out of their asses and exposed their own APIs into their plugin data.  I actually think that BukGet's success has stopped them from even thinking about it.

**Comment by DMarby** [comment]
Closing this due to the project not being active anymore, please see https://bukget.org/news/BukGet-Winding-Down/ for more details. For SpigotMC plugins, I'd recommend taking a look at https://spiget.org
